### ISSUE TITLE
Upgrade to angular 7 or 8

### ISSUE THREAD

**Issue by nikklass** [ihappyk/AppName#1]
Hi,
How would we upgrade this to angular 7 or 8?
Regards
Nikk

**Comment by ihappyk** [comment]
@nikklass its simple .
you can check this [link](https://www.google.com/search?q=migration+to+angular+7&oq=migration+to+angular+7+&aqs=chrome..69i57j0l2.6765j0j7&sourceid=chrome&ie=UTF-8) , see the first three results will help.

**Comment by nikklass** [comment]
Thanks
