### ISSUE TITLE
Springboot Links superseding angular links

### ISSUE THREAD

**Issue by nikklass** [ihappyk/AppName#2]
Hi,

I have managed to set up this repo in angular 8 and configured a few links both for the frontend side(angular 8) and backend api(springboot/java). When i go to the home page it opens the page fine. However when i go to a link e.g. http://localhost:8080/news, the app keeps checking for api links and throws an exception that the link does not exist - 
```
Fri Jul 26 16:09:18 EAT 2019
There was an unexpected error (type=Not Found, status=404).
```
If i go to the AppName-UI directory and run the command: 

> ng serve

 i can see the page using http://localhost:4200/news

How do i go about this and show this page from localhost:8080?

Thanks.

**Comment by ihappyk** [comment]
need more information , can you post the console error?

**Comment by nikklass** [comment]
I am using spring security on my backend and it keeps giving  me this error when i access a link like: http://localhost:8080/news

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Jul 29 09:58:34 EAT 2019
There was an unexpected error (type=Not Found, status=404).
No message available
```

**Comment by nikklass** [comment]
If i create a rest endpoint for "news", the page opens the backend endpoint, and not the angular page!! How do I ensure rest endpoints remain as backend, and angular routes are processed as frontend?

**Comment by ihappyk** [comment]
@nikklass i guess there its routing issue , try adding #news in the url and see

**Comment by nikklass** [comment]
Thanks.

The link below worked for me:

https://keepgrowing.in/java/springboot/make-spring-boot-surrender-routing-control-to-angular/

Regards,
Nikk
